### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by hanyamin** [daijifeng001/R-FCN#4]
HI @daijifeng001 
 when I use R-FCN for windows.  when I Run rfcn_build.m (I have got the caffe mex for windwos first),something wrong happened . Error message is as follows
Error using mex
Microsoft (R) Manifest Tool version 6.3.9600.17298
Copyright (c) Microsoft Corporation 2012.
All rights reserved.
mt : general error c101008d: Failed to write the updated manifest to the resource of file
"H:\R-FCN-master\bin\nms_mex.mexw64". The operation failed.
Error in rfcn_build (line 14)
  mex -O -outdir bin ...
My running environment : matlab2015a vs2013 cuda7.5  gpu:NVIDIA Quadro K2100M
Eager for your kind reply
Yamin

**Comment by daijifeng001** [comment]
Hi,

This should be a compiler configuration problem instead of a code bug. Please check it on search engines. 

https://www.bing.com/search?q=+Failed+to+write+the+updated+manifest+to+the+resource+of+file&qs=n&pq=failed+to+write+the+updated+manifest+to+the+resource+of+file&sc=0-0&sp=-1&sk=&intlF=1&FORM=TIPEN1
